It adds that VirtualBox is used on Windows
ustclug/Linux101-docs pull request #17
Opened 2021-07-07 14:13 UTC by HUGHNew

as the implement of [issue#15](https://github.com/ustclug/Linux101-docs/issues/15)

2021-07-08 06:53 UTC, iBug commented on docs/Ch01/index.md
> +    安装过程基本与 MacOS 下安装 VirtualBox 一致，也可以参考 Windows 安装 VMware ，两者大致相当
Mac 的操作系统的官方正式名称应该叫 macOS

2021-07-08 16:45 UTC, taoky commented on docs/Ch01/index.md
> +    不过需要注意的是，全屏使用需要下载 VirtualBox 增强工具
我记得装 VirtualBox 增强工具要装 `build-essential`（上面博客的链接里也提到了）。如果只要全屏的话，似乎装 <https://packages.ubuntu.com/search?keywords=virtualbox-guest-x11> 就行。

新手向的增强工具安装可以放在附录里？（要考虑到这个时候还不知道怎么使用 `sudo apt install` 安装程序）

2021-07-09 15:35 UTC, HUGHNew commented on docs/Ch01/index.md
> +    不过需要注意的是，全屏使用需要下载 VirtualBox 增强工具
似乎只需要鼠标点击就好了，不需要输入指令。参考一篇博客<https://blog.csdn.net/hahahaqwe123/article/details/109161137>，我印象中也是这样，只是需要自己输入密码，我过两天重装个镜像截图流程。

2021-07-14 16:04 UTC, HUGHNew commented on docs/Ch01/index.md
> +    不过需要注意的是，全屏使用需要下载 VirtualBox 增强工具
编写组的镜像在 VirtualBox 上可以直接全屏，我就懒得下Ubuntu来写安装增强工具的内容了，顺手贴了个博客。
补充了一点ova镜像的使用，需要在文档中留utsc账号的密码？

2021-07-14 16:26 UTC, taoky requested changes

2021-07-14 16:26 UTC, taoky commented on docs/Ch01/supplement.md
> +当然，我们可以看到，没有一个稳定的方案可以不加修改地直接运行 Linux 程序，直到 WSL 出现。WSL 由微软开发，可以在 64 位的 Windows 10 和 Windows Server 2019 上运行 ELF 格式的 Linux 程序（Windows的官方[安装指南](https://docs.microsoft.com/zh-cn/windows/wsl/install-win10
```suggestion
当然，我们可以看到，没有一个稳定的方案可以不加修改地直接运行 Linux 程序，直到 WSL 出现。WSL 由微软开发，可以在 64 位的 Windows 10 和 Windows Server 2019 上运行 ELF 格式的 Linux 程序（安装方法详见 WSL 的官方[安装指南](https://docs.microsoft.com/zh-cn/windows/wsl/install-win10）。
```

2021-07-14 16:26 UTC, taoky commented on docs/Ch01/index.md
> +    ova 镜像（虚拟硬盘格式）为如下提供的 Xubuntu 镜像，但使用过程跟下面两篇供参考的博客稍有不同。
下面已经写了「若已经安装了上述虚拟机管理软件，则可以直接双击打开虚拟机镜像」，所以我感觉这段不用加。

2021-07-14 16:28 UTC, taoky commented on docs/Ch01/index.md
> +    不过需要注意的是，全屏使用需要下载 VirtualBox 增强工具
> 编写组的镜像在 VirtualBox 上可以直接全屏，我就懒得下Ubuntu来写安装增强工具的内容了，顺手贴了个博客。
> 补充了一点ova镜像的使用，需要在文档中留utsc账号的密码？

密码下面已经提到了，所以不需要加。另外准备明年 101 活动之前把镜像升级到 20.04。

其实如果只是支持全屏的话是不用装增强工具的……但是要支持共享文件夹等特性的话是要的。

2021-07-15 01:54 UTC, HUGHNew commented on docs/Ch01/index.md
> +    ova 镜像（虚拟硬盘格式）为如下提供的 Xubuntu 镜像，但使用过程跟下面两篇供参考的博客稍有不同。
把这个 tip 删了，导入的图片放在了之后**使用**的位置

2021-07-17 05:31 UTC, HUGHNew commented on docs/Ch01/index.md
> +    不过需要注意的是，全屏使用需要下载 VirtualBox 增强工具
把那句话删了，改在前面，简述了共享文件夹功能参考，复用了你那片博客

2021-09-09 03:00 UTC, HUGHNew commented on docs/Ch01/index.md
> +    不过需要注意的是，全屏使用需要下载 VirtualBox 增强工具
> > 编写组的镜像在 VirtualBox 上可以直接全屏，我就懒得下Ubuntu来写安装增强工具的内容了，顺手贴了个博客。
> > 补充了一点ova镜像的使用，需要在文档中留utsc账号的密码？
> 
> 密码下面已经提到了，所以不需要加。另外准备明年 101 活动之前把镜像升级到 20.04。
> 
> 其实如果只是支持全屏的话是不用装增强工具的……但是要支持共享文件夹等特性的话是要的。

今天装UOS的时候发现了 支持全屏确实不需要增强工具 改虚拟机的分辨率就行了 但根据VirtualBox窗口自动改分辨率我不清楚是自带的功能还是增强的功能了

2023-02-19 07:55 UTC, taoky approved these changes

2023-02-19 08:16 UTC, iBug approved these changes

2023-02-19 08:17 UTC, iBug commented
Closes #15

2023-02-19 08:17 UTC, merged