Ch01: Add guide to configure vm in apple silicon machines
ustclug/Linux101-docs pull request #32
Opened 2023-02-18 16:30 UTC by bc-li

由于我 arch 学得比较烂所以可能 

> X86_64 架构和 ARM64 两种架构都是什么？它们有什么区别？

这个问题写的不是很好...

其他应该只是一个正常的内容，先装 Ubuntu Server 再安装桌面环境就可以了。不过想用好是相当折腾的，不知道 UTM 效果如何。

2023-02-18 16:35 UTC, taoky commented
得过一下 prettier（

2023-02-18 16:57 UTC, taoky commented
正文安装 VM 那个部分也得加一个短说明，给出跳到补充说明里面的链接。

2023-02-18 17:00 UTC, zeyugao commented
以及可以说一下这个应该用的是ubuntu ports源而不是常用的ubuntu源

2023-02-18 17:13 UTC, iBug commented on docs/Ch01/supplement.md
> +可供参考的内容：
此处下面的三个链接建议使用 `<ul>`。

2023-02-18 17:17 UTC, iBug requested changes

2023-02-18 17:17 UTC, iBug commented on docs/Ch01/supplement.md
> +可供参考的内容：
此处下面的三个链接建议使用 `<ul>`。

2023-02-18 17:17 UTC, iBug commented on docs/Ch01/supplement.md
> +### 什么是 Apple Silicon？ {#apple-silicon}
*什么是 Apple Silicon？* 和 *X86_64 架构和 ARM64 两种架构都是什么？它们有什么区别？* 这两个 H3 我个人认为写成 `!!! question` 会好一些，它们与安装虚拟机相关，但不是直接关联。

2023-02-18 17:17 UTC, iBug commented on docs/Ch01/supplement.md
> +### X86_64 架构和 ARM64 两种架构都是什么？它们有什么区别？ {#x86_64-arm64}
更常见或更正式的写法是 **x86-64**（不是下划线，例如[维基百科](https://en.wikipedia.org/wiki/X86-64)）。同理 hashtag 中的下划线也可以换成短线。

2023-02-18 17:17 UTC, iBug commented on docs/Ch01/supplement.md
> +-   Ubuntu 22.04.1 LTS (Jellyfish)：2022 年 9 月 20 日之后的 daily development builds 可以使用。官方常规 release 的版本无法运行。
Jellyfish 前面的单词不见了？

2023-02-18 17:17 UTC, iBug commented on docs/Ch01/supplement.md
> +如果你不需要远程连接你的虚拟机，你可以不安装 open-ssh 包（当然，你可以在之后自行安装）。
这个包真的叫做 `open-ssh` 吗？

2023-02-18 17:19 UTC, iBug requested changes

2023-02-18 17:19 UTC, iBug commented on docs/Ch01/index.md
> +    请注意，本节中在 macOS 下安装虚拟机的步骤只适用于使用 Intel 处理器的 Mac。如果你使用的是基于 Apple Silicon 的 Mac，请参见[在使用 Apple Silicon 处理器的机型上配置 Linux 虚拟机](/Ch01/supplement/#configure-vm-in-apple-silicon)。
在 MkDocs 文档内部链接请使用源文件的相对路径，例如上面两行的 `supplement.md#wsl`。

2023-02-19 02:09 UTC, RTXUX commented on docs/Ch01/supplement.md
> +    如果你通过上面的步骤安装好了带有图形界面的 Ubuntu 虚拟机，你可能会发现在设置中并不能调整图形界面的分辨率（它被限制在了 1024*768）。简而言之，这是因为 VMWare 为 Linux 适配的图形驱动 `vmwgfx` 在 5.14 版本之后的内核才被包含。而 Ubuntu 20.04 原生 Linux 内核是 5.4 版本的，并不包含 VMWare 适配的驱动。所以如果你想
`vmwgfx` 应该是 5.14 之后才支持 ARM64，它很早就在内核里了

2023-02-19 03:27 UTC, bc-li commented on docs/Ch01/supplement.md
> +    如果你通过上面的步骤安装好了带有图形界面的 Ubuntu 虚拟机，你可能会发现在设置中并不能调整图形界面的分辨率（它被限制在了 1024*768）。简而言之，这是因为 VMWare 为 Linux 适配的图形驱动 `vmwgfx` 在 5.14 版本之后的内核才被包含。而 Ubuntu 20.04 原生 Linux 内核是 5.4 版本的，并不包含 VMWare 适配的驱动。所以如果你想
在 d96ee86 中更改了描述

2023-02-19 03:28 UTC, bc-li commented on docs/Ch01/index.md
> +    请注意，本节中在 macOS 下安装虚拟机的步骤只适用于使用 Intel 处理器的 Mac。如果你使用的是基于 Apple Silicon 的 Mac，请参见[在使用 Apple Silicon 处理器的机型上配置 Linux 虚拟机](/Ch01/supplement/#configure-vm-in-apple-silicon)。
> 在 MkDocs 文档内部链接请使用源文件的相对路径，例如上面两行的 `supplement.md#wsl`。

已经在 769c145 中修改

2023-02-19 03:32 UTC, bc-li commented on docs/Ch01/supplement.md
> +可供参考的内容：
> 此处下面的三个链接建议使用 `<ul>`。

已在 d96ee86 中更改为 markdown 语法的 unordered list。

2023-02-19 03:33 UTC, bc-li commented on docs/Ch01/supplement.md
> +### 什么是 Apple Silicon？ {#apple-silicon}
> _什么是 Apple Silicon？_ 和 _X86_64 架构和 ARM64 两种架构都是什么？它们有什么区别？_ 这两个 H3 我个人认为写成 `!!! question` 会好一些，它们与安装虚拟机相关，但不是直接关联。

已在 d96ee86 中更改为 `!!!question`。

2023-02-19 03:34 UTC, bc-li commented on docs/Ch01/supplement.md
> +### X86_64 架构和 ARM64 两种架构都是什么？它们有什么区别？ {#x86_64-arm64}
> 更常见或更正式的写法是 **x86-64**（不是下划线，例如[维基百科](https://en.wikipedia.org/wiki/X86-64)）。同理 hashtag 中的下划线也可以换成短线。

已在 d96ee86 中修改为统一使用 x86-64。

2023-02-19 03:35 UTC, bc-li commented on docs/Ch01/supplement.md
> +-   Ubuntu 22.04.1 LTS (Jellyfish)：2022 年 9 月 20 日之后的 daily development builds 可以使用。官方常规 release 的版本无法运行。
> Jellyfish 前面的单词不见了？

已在 d96ee86 中更正为 Jammy Jellyfish。

2023-02-19 03:36 UTC, bc-li commented on docs/Ch01/supplement.md
> +如果你不需要远程连接你的虚拟机，你可以不安装 open-ssh 包（当然，你可以在之后自行安装）。
> 这个包真的叫做 `open-ssh` 吗？

在 d96ee86 中更改了描述。

2023-02-19 03:59 UTC, iBug commented
修改意见无需逐个回复，点击 Resolve conversation 按钮即可，这样方便保持 thread 的整洁，GitHub 会自动折叠标记为 resolved 的修改讨论。

![image](https://user-images.githubusercontent.com/7273074/219919420-51b93591-6303-43d0-9323-a8c72ed16180.png)

2023-02-19 04:04 UTC, iBug requested changes

2023-02-19 04:04 UTC, iBug commented on docs/Ch01/supplement.md
> +    !!! quote "Apple Silicon（苹果硅）是对苹果公司使用 ARM 架构设计的单芯片系统（SoC）和封装体系（SiP）处理器之总称。它广泛运用在 iPhone、iPad、Mac 和 Apple Watch 以及 HomePod 和 Apple TV 等苹果公司产品。 - Wikipedia"
这个地方有必要保留嵌套的 `!!! quote` 吗？

2023-02-19 04:04 UTC, iBug commented on docs/Ch01/supplement.md
> +你可以在 [mirrors.ustc.edu.cn](https://mirrors.ustc.edu.cn/) 上获取安装镜像。
链接文字可以考虑换成镜像站的名称

2023-02-19 04:05 UTC, iBug commented on docs/Ch01/supplement.md
> +    如果你通过上面的步骤安装好了带有图形界面的 Ubuntu 虚拟机，你可能会发现在设置中并不能调整图形界面的分辨率（它被限制在了 1024*768）。简而言之，这是因为 VMWare 为 Linux 适配的图形驱动 `vmwgfx` 在 5.14 版本之后的内核才被包含。而 Ubuntu 20.04 原生 Linux 内核是 5.4 版本的，并不包含 VMWare 适配的驱动。所以如果你想
U 20.04 的 HWE 内核已经到 5.15 了，还有必要自己编译 5.14 吗？

2023-02-19 05:35 UTC, zeyugao commented on docs/Ch01/supplement.md
> +#### 下载 VMWare Fusion 22H2 Tech Preview {#download-vmware-fusion}
已经过了Tech Preview阶段了，Fusion 13发布了正式版 https://blogs.vmware.com/teamfusion/2022/11/fusion-13-pro-and-player-are-here.html

2023-02-19 05:35 UTC, zeyugao commented on docs/Ch01/supplement.md
> +* Ubuntu 20.04.5 LTS (Focal Fossa)：可以使用，需要经过改动才能修改图形界面的分辨率。
这些支持情况都是针对于Tech Preview而言的，正式版的支持情况还需要看看，非TLS的版本可以不加上支持情况？

https://docs.vmware.com/en/VMware-Fusion/13.0/rn/vmware-fusion-130-release-notes/index.html 里面提到了22.04支持情况，但是13.0.1更新没有说明支持情况是否有更新

2023-02-19 05:35 UTC, zeyugao commented on docs/Ch01/supplement.md
> +	如果你通过上面的步骤安装好了带有图形界面的 Ubuntu 虚拟机，你可能会发现在设置中并不能调整图形界面的分辨率（它被限制在了 1024*768）。简而言之，这是因为 VMWare 为 Linux 适配的图形驱动 `vmwgfx` 在 5.14 版本之后的内核才被包含。而 Ubuntu 20.04 原生 Linux 内核是 5.4 版本的，并不包含 VMWare 适配的驱动。所以如果你想修改
查了一下20.04.5自带的Kernel是5.15的？

2023-02-19 05:35 UTC, zeyugao commented on docs/Ch01/supplement.md
> +[Fusion 22H2 Tech Preview Testing Guide](https://communities.vmware.com/t5/Fusion-22H2-Tech-Preview/Fusion-22H2-Tech-Preview-Testing-Guide/ta-p/2867908)
给tech preview的都可以换成这个

https://communities.vmware.com/t5/VMware-Fusion-Documents/The-Unofficial-Fusion-13-for-Apple-Silicon-Companion-Guide/ta-p/2939907/jump-to/first-unread-message

2023-02-19 05:35 UTC, zeyugao commented on docs/Ch01/supplement.md
> +* Ubuntu 20.04.5 LTS (Focal Fossa)：可以使用，需要经过改动才能修改图形界面的分辨率。
好像13没啥区别，但是22.04.2快要出了，Expected: 2023-02-23
https://launchpad.net/ubuntu/+milestone/ubuntu-22.04.2

2023-02-19 05:38 UTC, iBug commented on docs/Ch01/supplement.md
> +	如果你通过上面的步骤安装好了带有图形界面的 Ubuntu 虚拟机，你可能会发现在设置中并不能调整图形界面的分辨率（它被限制在了 1024*768）。简而言之，这是因为 VMWare 为 Linux 适配的图形驱动 `vmwgfx` 在 5.14 版本之后的内核才被包含。而 Ubuntu 20.04 原生 Linux 内核是 5.4 版本的，并不包含 VMWare 适配的驱动。所以如果你想修改
20.04.x 自带的 kernel 都是 5.4.x 的，这是 LTS 稳定性保证的一部分。Kernel 5.15 需要通过 HWE 获取（`apt install linux-image-generic-hwe-20.04`）。

2023-02-19 06:17 UTC, bc-li commented on docs/Ch01/supplement.md
> +    如果你通过上面的步骤安装好了带有图形界面的 Ubuntu 虚拟机，你可能会发现在设置中并不能调整图形界面的分辨率（它被限制在了 1024*768）。简而言之，这是因为 VMWare 为 Linux 适配的图形驱动 `vmwgfx` 在 5.14 版本之后的内核才被包含。而 Ubuntu 20.04 原生 Linux 内核是 5.4 版本的，并不包含 VMWare 适配的驱动。所以如果你想
> U 20.04 的 HWE 内核已经到 5.15 了，还有必要自己编译 5.14 吗？

我刚才测试了一下，确实可以直接用 HWE 了。稍后我修改一下这段内容

2023-02-20 07:04 UTC, zeyugao commented on docs/Ch01/supplement.md
> +-   [Fusion 22H2 Tech Preview Testing Guide](https://communities.vmware.com/t5/Fusion-22H2-Tech-Preview/Fusion-22H2-Tech-Preview-Testing-Guide/ta-p/2867908)
这两个Tech Preview的链接可以删掉

2023-02-20 07:11 UTC, zeyugao commented on docs/Ch01/supplement.md
> +-   Ubuntu 22.04.1 LTS (Jammy Jellyfish)：2022 年 9 月 20 日之后的 daily development builds 可以使用。官方常规 release 的版本无法运行。
这里可以直接把22.04.2写上去了，等到merge接近正式发布了

2023-02-20 07:12 UTC, bc-li commented on docs/Ch01/supplement.md
> +-   [Fusion 22H2 Tech Preview Testing Guide](https://communities.vmware.com/t5/Fusion-22H2-Tech-Preview/Fusion-22H2-Tech-Preview-Testing-Guide/ta-p/2867908)
两个 Tech Preview 的文档和 The Unofficial Fusion 13 for Apple Silicon Companion Guide 的内容好像还是有一些内容不是重合的（例如升级 Kernel 的部分可以在老的 TP testing docs 中找到）。我个人觉得如果有一些问题 Unofficial Guide 里面无法 cover，还是可以翻翻老的内容找找有没有能用的试一试。也许需要注明？如果还是觉得不合适的话，我就拿掉

2023-02-20 17:02 UTC, iBug reviewed
根据 [记号约定](https://101.lug.ustc.edu.cn/notations/)，虚拟机内的用户名是 `ustc`。如果方便的话考虑重新截图 `6.png` 和 `7.png`.

2023-02-21 10:12 UTC, taoky commented
图有点大了，可以考虑压一下（缩一下分辨率，或者拿 ImageOptim (macOS) 之类的软件压缩）。因为最后 squash 所以对 clone 仓库的人来讲应该没什么影响。

2023-03-10 16:08 UTC, RTXUX approved these changes
LGTM

2023-03-10 17:15 UTC, iBug requested changes

2023-03-10 17:15 UTC, iBug commented on docs/Ch01/supplement.md
> +    Apple Silicon（苹果硅）是对苹果公司使用 ARM 架构设计的单芯片系统（SoC）和封装体系（SiP）处理器之总称。它广泛运用在 iPhone、iPad、Mac 和 Apple Watch 以及 HomePod 和 Apple TV 等苹果公司产品。(from Wikipedia)
`(from Wikipedia)` 这个后缀是不是改成 `[^1]` 这样的脚注会好一点

2023-03-10 17:15 UTC, iBug commented on docs/Ch01/supplement.md
> +    ARM64（也被称为 AArch64），是 ARM 公司推出的 64 位处理器架构。它被广泛用于移动设备、嵌入式系统和服务器领域。与之前的 32 位架构相比，它具有更高的性能和更好的功耗管理。
*ARM64，是……* 这个逗号是多余的

2023-03-10 17:15 UTC, iBug commented on docs/Ch01/supplement.md
> +    ```bash
代码块和其前后的 `<p>` 都留个空行比较好

2023-03-11 12:06 UTC, iBug requested changes

2023-03-11 12:06 UTC, iBug commented on docs/Ch01/supplement.md
> +[^1]: [Apple silicon - Wikipedia](https://en.wikipedia.org/wiki/Apple_silicon)
此处前面应该有一个 H2 “引用来源”，参考其他文件补上这个 H2 吧

2023-03-11 12:25 UTC, iBug commented on docs/Ch01/supplement.md
> +-   [Apple silicon - Wikipedia](https://en.wikipedia.org/wiki/Apple_silicon)
footnote 和带标题的链接并不冲突，参考 {Ch01,Ch03,Ch07}/index.md

2023-03-11 12:31 UTC, zeyugao approved these changes

2023-03-11 13:23 UTC, iBug approved these changes

2023-03-11 13:46 UTC, merged